version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  flask-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: flask-app
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      redis:
        condition: service_started

  test-runner:
    build:
      context: ./app
      dockerfile: Dockerfile  # Use the same image as flask-app
    container_name: test-runner
    depends_on:
      flask-app:
        condition: service_healthy  # Ensures flask-app is ready before running tests
    command: ["pytest", "tests/"]  # Runs pytest automatically
