version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  flask-app:
    build: .
    container_name: flask-app
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      redis:
        condition: service_started
